# Generated by Django 2.2.3 on 2019-08-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='s',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='phone',
            name='s',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='computer',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
